### ISSUE TITLE
Provide Typescript definitions

### ISSUE THREAD

**Issue by maxime1992** [ctavan/node-getenv#12]
Hi,

it'd be really handy to have the type definitions published as part of the package or directly under the `@types/getenv` for example.

**Comment by ctavan** [comment]
@maxime1992 great idea! Since I don't use typescript at the moment I don't have a personal motivation to implement this right now.

However, if you want to supply a pull request I'm more than happy to review and merge it!

**Comment by impankratov** [comment]
Let's see if we get typings accepted https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29607

**Comment by ctavan** [comment]
Thanks to @impankratov TypeScript definitions are available from the `@types/getenv` package now and this has finally also been [documented in the README](https://github.com/ctavan/node-getenv#installation).

I've also filed a PR to align the type definition version with the latest getenv module version: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38995
