### ISSUE TITLE
@types/getenv out of sync for getenv.array()

### ISSUE THREAD

**Issue by pocin** [ctavan/node-getenv#21]
hey! Not sure how exactly @types/getenv are generated, but the signature for `getenv.array()` doesnt have the separator argument 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/getenv/index.d.ts#L86=

Is this the place to fix it or in the DefinitelyTyped repo?

**Comment by ctavan** [comment]
The types are not generated but have been written manually in the DefinitelyTyped repo. Feel free to propose a pull request over there.
