### ISSUE TITLE
Provide support for parsing objects

### ISSUE THREAD

**Issue by goloroden** [ctavan/node-getenv#4]
It would be awesome if there was also a

    getenv.object(...)

function that parses the given environment variable as JSON. Basically this should be the same as:

    JSON.parse(getenv.string(...));

And, of course, additionally it would be awesome to be able to provide a default value in case parsing fails.

**Comment by dohse** [comment]
A pull request for that is welcome.

A parsing error should be an error though. The default should be taken if no value is configured.

**Comment by ctavan** [comment]
There is already [getenv.multi()](https://github.com/ctavan/node-getenv#envmultispec) which is somewhat different but allows you to create objects from environment variables.

What is your precise use case? I wonder if it is good practice to store JSON in environment variables?

**Comment by ctavan** [comment]
Closing this for now. Feel free to reopen if this becomes relevant again.
