### ISSUE TITLE
Support for object fallbacks

### ISSUE THREAD

**Issue by sauramirez** [ctavan/node-getenv#9]
Would it make sense to have an object fallback that would pass for the environments you send but fails for the others?

Therefore instead of disabling all of the fallbacks some of them would be optionals and other environments could be required. For example:

getenv.int('TEST_ENV', {
  development: 3
})

This would depend on the NODE_ENV being set to development, and it would fail on a different environment.

Thanks.

**Comment by ctavan** [comment]
@sauramirez thanks for this suggestion. I think it complicates the interface of the module quite a bit and I would prefer to keep it as simple as it is right now. 

You can still disable fallbacks in production alltogether and consider your defaults being testing-only: https://github.com/ctavan/node-getenv#envdisablefallbacks

Would that be an option for you as well?

**Comment by sauramirez** [comment]
we didn't want to disable all of the fallbacks since we still use some of them and override them only in a few environments.
I think I would prefer a flag instead of it being the default behavior in order to not complicate the interface and the implementation is basically just checking for an object and returning the environment.
But if you think it would complicate it too much I can just create a wrapper.

**Comment by ctavan** [comment]
@sauramirez feel free to create a pull request from your patch and I'll have another look!
